"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']

# DATA_FILES includes non-python files needed by the app.
# We include the 'assets' folder recursively and the '.env' file 
# because main.py relies on loading configuration from it.
DATA_FILES = [
    'assets', 
    '.env' 
]

# OPTIONS configures how py2app builds the application bundle.
OPTIONS = {
    'argv_emulation': True,
    
    # 'packages' ensures these third-party libraries are fully included.
    # We include 'pygame' (from pygame-ce), 'dotenv' (from python-dotenv), and 'requests'.
    'packages': ['pygame', 'dotenv', 'requests', 'urllib3', 'certifi', 'idna', 'charset_normalizer'],
    
    # 'includes' forces py2app to include your local project folders 
    # as modules, ensuring imports like 'import scenes.MainMenu' work.
    'includes': ['elements', 'scenes', 'sweeper', 'utils'],
    
    # Optional: If you want to exclude things to save space
    'excludes': ['.git', '.gitignore']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)